# Generated by Django 3.2.9 on 2021-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car2_line2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car2',
            name='line',
            field=models.ManyToManyField(to='cars.Line2'),
        ),
    ]
