# Generated by Django 3.2.9 on 2021-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_deleted_line2_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car2',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
